on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.0
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
        remote_path: /home/sboc4997/public_html/coba-ssh.sbos.my.id
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_port: 2223
